# U-DAWS-Dockerfiles Travis-CI Build configuration

sudo: required

language: python

python:
  - "3.6"

services:
  - docker

env:
  global:
    - DOCKERHUB_ORG=medforomics
    - DEPLOY_BRANCH=master

install:
  - pip install -r tests/requirements.txt

stages:
  - build
  - test
  - name: deploy
    if: branch = master

before_script:
  - git fetch --branch=master --depth=3

jobs:
  include:
    - stage: build
      script: sh ci/build.sh
    - stage: test
      script: nosetests
      script: sh ci/test.sh
    - stage: deploy
      script: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      script: sh ci/deploy.sh
