# U-DAWS-Dockerfiles Travis-CI Build configuration

sudo: required

language: python

python:
  - "3.6"

services:
  - docker

env:
  global:
    - DOCKERHUB_ORG=medforomics
    - DEPLOY_BRANCH=master

install:
  - pip install -r tests/requirements.txt

stages:
  - build
  - test
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: build
      script: ./build-ci.sh
    - stage: test
      script: nosetests
      script: ./test-ci.sh
    - stage: deploy
      script: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      script: ./deploy-ci.sh
