# U-DAWS-Dockerfiles Travis-CI Build configuration

sudo: required

python:
  - "3.6"

services:
  - docker

env:
  global:
    - DEPLOY_BRANCH=master
    - DOCKERHUB_ORG=medforomics


jobs:
  include:
    - stage: build docker image
      script:
      - ./build-ci.sh
    - stage: test
      script: docker run --rm $DOCKER_USERNAME/travis-ci-build-stages-demo cat hello.txt
    - script: docker run --rm $DOCKER_USERNAME/travis-ci-build-stages-demo cat hello.txt

jobs:
  build:
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install python requirements
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r tests/requirements.txt
      - run:
          name: Build Docker Images
          command: ./build-ci.sh
      - run:
          name: Run python code that tests the Docker Images
          command: |
            . venv/bin/activate
            nosetests
            ./test-ci.sh
#      - deploy:
#          name: Deploy Docker Images
#          command: |
#            if [ "${BRANCH}" == "${DEPLOY_BRANCH}" ]; then
#              docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
#              ./deploy-ci.sh
#            fi
