# U-DAWS-Dockerfiles Travis-CI Build configuration

sudo: required

language: python

python:
  - "3.6"

services:
  - docker

env:
  global:
    - DOCKERHUB_ORG=medforomics
    - DEPLOY_BRANCH=master

install:
  - pip install -r tests/requirements.txt

stages:
  - build
  - test
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: build
      script: bash ci/build.sh
    - stage: test
      script: nosetests
      script: bash ci/test.sh
    - stage: deploy
      if: type != pull_request
      script: bash ci/deploy.sh
