sudo: required
language: python
python:
- '3.6'
services:
- docker
env:
  global:
  - DOCKERHUB_ORG=medforomics
  - DEPLOY_BRANCH=master
  matrix:
  - secure: LQYgNoTycTuf7rAwlwtBbaegGk5/rIVeUTQihY8y0VEnAd/68Kxconc9JklPdLQ6u6N+9L0m6laeAuNl8+SOQLUJsf0CriqJynO59bQatyLZiOawX6QRDZFQghr4RuMdM1MD/im+NjjPncFjwcnLIaTPmOzcN7ZP28BmyYpPhB+P54Vf00dRZzt3jDL2oozWECF3G64RTRKnKj7all9GKSv49bqXSKI1EWfIBCwmI+ijWCMQME9o865uJDu2m5D22wtsN5oja1OtvPyHc1Rel3fG7uM48K8dciQRA3//Wb9diaddiYLnZLGOIyQ98Y6SvtE9Jba2Rh2l36Gw8sDr6EsSCm1vDvxVepC1jR/QIixMRKoPe5EfAFCU+gXGAUxpoYAMbN3/h6YpCtLLgrnAZWErHUVPKrMQIzWW+0UPAAFFbkZ6F+GqlPh12IY5iDq7YXCPuTjC2rY8ozkdoj+16+qJvElx67U9/lU1dPijigZDM1FDJ8ojv6QieQqDYeMtX8QAc3470qs4WzsJLSwQMSwJ7iFtpZT2wxwyUYpq32B6WR8aZ+XeeK8sohhIR4q5Q9k0KlMhrphFqQd0tCQBypsvbNw8modF06l9maD0pV6F/8k2BPMOUxpyc4nEDHiFtslOksrVmvEAgGVSArZnNw6P0nxJ1ROxL0oQZ9GWpOY=
  - secure: CtpBTGNu5Hrpaod4MnVga/g8oflWn0F2UgGzj3Gdn3EmaBD3tvD9GLczR1xcDIyw9HLEDK+8fikDULV0BKGbnD+z/Brf+GBqQXrNfxU8F4s8vXQsD1baq/ifHGybmObr2tMHegxhJf5WUsunko6L90xHnQ5aNCOZlz97RIfVtdt8bsWSLZSdeTd50ipOHftS6upo23ngh2Ak7d/83lzeVKqAsQp5PzJPVZVJI+nTCAUvWjCzrdwBzdF8dOtKa56oFpKeC13G/IK3TpQXEasMqAh7E9FF9o4hWrf3JIv2uhIwl8jScaq9TJdLYVhehOE1zzdXAbK4M3rV+dR6qaXdl9XExW9Tni/WESSPjN6LN5ZXuUeW0TOn9iCWlihbijGedJwprnVjnQK7aS9RynJ+L7w8+fJAS4jNu0nVTh+cbVFqt3FZ33SBuu8F2ZX5CV/lhzO8P7TU+QcCIRSuJBPCY/xeYbCDbSA5zefNmEjRNbVhGOlTyLwmhgQ2mHSdXhRp+MpWoRcVRLBqt4IdmUQWvHCZZSxTSyJr3GDKInPhmsHdo4W+vv5TLOGzORatVk9NzH0v6Ai1VxI0ujBjmNtP8/BXOSIOJVu6jCrsg6HQukGxvQJWnNkWnRp+/5Q5uRpWrhOcZ4k9f9XgKugqEmvBZPGAMHBhzdpPwv7IhJaY8KM=
addons:
  apt:
    packages:
      - docker-ce
install:
- pip install -r tests/requirements.txt
stages:
- build
- test
- name: deploy
  if: branch = master
jobs:
  include:
  - stage: build
    script: bash ci/build.sh
  - stage: test
    script: bash ci/test.sh
  - stage: deploy
    if: type != pull_request
    script: bash ci/deploy.sh
