# U-DAWS-Dockerfiles Travis-CI Build configuration

sudo: required

language: python

python:
  - "3.6"

services:
  - docker

env:
  global:
    - DOCKERHUB_ORG=medforomics


install:
  - pip install -r tests/requirements.txt

stages:
  - build


jobs:
  include:
    - stage: build
      script: ./build-ci.sh
