sudo: required
language: python
python:
- '3.6'
services:
- docker
env:
  global:
  - DOCKERHUB_ORG=medforomics
  - DEPLOY_BRANCH=master
  - DOCKERHUB_USERNAME=udawsci
addons:
  apt:
    packages:
      - docker-ce
install:
- pip install -r tests/requirements.txt
stages:
- build
- test
- name: deploy
  if: branch = master
jobs:
  include:
  - stage: build
    script: bash ci/build.sh
  - stage: test
    script: bash ci/test.sh
  - stage: deploy
    if: type != pull_request
    script: bash ci/deploy.sh
